### ISSUE TITLE
Label file format

### ISSUE THREAD

**Issue by bman7777** [Noahs-ARK/soft_patterns#1]
The document says that "the labels file contains the label."  What format is that label in?  Is it a framenet label?  or something else?  What if a given sentence has more than one label?  Should they be comma delimited?

**Comment by roys174** [comment]
Sorry for the late reply. The label format is a number. We are assuming text classification, so each sentence has a single label, which is the document label. For instance, in sentiment analysis, you can mark 0 for negative and 1 for positive.
