### ISSUE TITLE
[Question]: Regarding the output of visualize.py

### ISSUE THREAD

**Issue by atreyasha** [Noahs-ARK/soft_patterns#8]
Hello all,

Thank you very much for developing the SoPa model framework. I am interested in extending parts of SoPa as I believe it has great potential for explainability while maintaining competitive (enough) performance.

As part of preliminary tests, I trained a model on the sample data provided here and tested the output of `visualize.py`. I directed stdout to a local log file and am seeing outputs such as the one below:

```
Pattern: 12 of length 3
Highest scoring spans:
0 0.335  b'HP noblest        HP efforts        #label=0'
1 0.333  b"HP it             HP 's             #label=1"
2 0.333  b'HP to             HP immerse        #label=0'
3 0.331  b'HP *START*        HP *START*        #label=1'
4 0.331  b"HP 's             HP somewhat       #label=0"
self-loops:   1.00 * escaping        +  0.54,  1.00 * carnahan        +  0.45,  1.01 * class           +  1.29
fwd 1s:       1.01 * relentless      + -0.61,  1.00 * drags           +  2.56
epsilons:                               0.47,                            0.59
```

As per my understanding, the highest scoring spans refers to the token spans that fit the i'th pattern with the highest probability. I am not sure as to what the next three lines starting with `self-loops`, `fwd 1s` and `epsilons` refer to.

Are these perhaps referring to the tokens with the highest probabilites for providing the three transition types given the pattern?

Thank you for your time.

**Comment by roys174** [comment]
Hi Atreya, happy you found SoPa interesting!

To your questions:

1. Yes, the highest scoring spans are the phrases that received the highest score for each pattern.
2. The other rows represent the different transition in that pattern. For instance, in the one you show here, we have a pattern of length 3:

X --> Y --> Z

Each transition also has a self-loop (3 self loops in total). The words you see there are the word with the closest vector to the transition vector. The fwd 1s represent the forward transitions (2 transitions in total) and the epsilons represent epsilon value (moving from X to Y / Y to Z without consuming a token). 

Hope this helps!

Best,
Roy

**Comment by atreyasha** [comment]
Hi @roys174, thank you for the explanation. If you have some time, I would like to follow-up.

I noticed in the main source code for training the `SoftPatternClassifier` that input sentences are padded both at the front and back with `*START*` and `*END*` tokens respectively depending on the maximum pattern length, for example here:

https://github.com/Noahs-ARK/soft_patterns/blob/591c79ff19d5f1a482cea9176ec4499493c18726/soft_patterns.py#L693

As a result of this, I noticed that the `visualize` workflow also shows patterns with the extra padded tokens, for example here:

```
0.331  b'HP *START*        HP *START*        #label=1'
```

My questions are:

1. What is the purpose of adding these extra (multiple) tokens at the front and back? I attempted to change the number of padding tokens to just 1 and the model still runs without error, which would make me think that the reason is probably for downstream interpretability.

2. Do you consider it an issue that multiple padding tokens also appear as highest-scoring patterns when visualizing the patterns for interpretability (for example as shown above)? I would imagine that the highest-scoring patterns should ignore the repetitive `*START*` and `*END*` padding tokens.

Thanks again for your time.
